import { chromium } from "playwright";
import { readFileSync } from "node:fs";
const svg = readFileSync(process.argv[2], "utf8");
const b = await chromium.launch();
const p = await (await b.newContext({ deviceScaleFactor: 1 })).newPage();
await p.setViewportSize({ width: 1024, height: 1024 });
await p.setContent(`<!doctype html><html><body style="margin:0">${svg}</body></html>`);
await p.locator("svg").screenshot({ path: process.argv[3], omitBackground: true });
await b.close();
console.log("saved", process.argv[3]);
